export {
  DASHBOARD_NAV_ITEMS,
  getAccessibleDashboardHref,
  getDashboardPathPageRequirements,
  getRequiredPagePermission,
  canAccessDashboardPath,
  getFirstAccessibleDashboardPath,
  resolvePostAuthDashboardHref,
  resolveDashboardLandingHref,
  getVisibleDashboardNavItems,
  isNavPathSelected,
} from "./dashboard-access";
export type { DashboardNavItem, DashboardNavSection, DashboardSidebarIconKey } from "./dashboard-nav.types";
export {
  getOperationalViewAnyOfForDashboardPath,
  userSatisfiesOperationalViewForDashboardPath,
} from "./operational-view-gate";
export { PAGE, ORG, HRMS, HRMS_LEAVE_APPROVE_ANY, HRMS_WORKFORCE_VIEW_ANY, flattenPermissionCodes } from "./permission-constants";
export {
  hasAnyOperational,
  hasPagePermission,
  canAccessRoute,
  hasPoolPage,
  hasDepartmentsPage,
  canPermissionCode,
  createPermissionCan,
  type PermissionChecker,
  type AuthPermissionArrays,
} from "./access-helpers";
export { CHAT_CLIENT_CAP_PRESET_NAMES, CHAT_CLIENT_CAP_PRESET_LABELS } from "./chat-client-cap-preset";
export {
  CHAT_BUNDLE_OPTIONS,
  isChatBundleCode,
  isGranularChatPermissionCode,
  pickAssignedChatBundle,
  type ChatBundleCode,
} from "./chat-bundles";
export {
  canAccessCompanyScopeFilters,
  canViewWebsiteDirectory,
} from "./company-scope-filter-access";
export { useChatApiGates } from "./use-chat-api-gates";
export {
  canAgentChatFromArrays,
  canShowAgentInboxNav,
  type AgentInboxEligibilityOptions,
  canMonitorFromArrays,
  canQaFromArrays,
  canChatReportsFromArrays,
  canWidgetSettingsFromArrays,
  canUseCopilotInboxFromArrays,
  canUseCopilotInbox,
  canAiAssistantTrainingFromArrays,
  canCopilotSetupFromArrays,
  canManageCopilotSetupFromArrays,
  canManagePlatformAiFromArrays,
  canAiAssistantFromArrays,
  canMonitorRoute,
  canAccessChatInbox,
  canAccessChatInboxFromChecker,
  canAccessChatMonitor,
  canAccessChatQa,
  canAnnotateQaMessage,
  canApproveTakeover,
  canAssignQaReview,
  canPlatformChatAudit,
  canRequestTakeover,
  canReviewQaSession,
  canSendGuestLink,
  canSupervisorCloseChat,
  canUseSupervisorTools,
  canViewChatReports,
  canAccessQaTeamReports,
  canWhisper,
  needsChatScopeFilters,
  buildChatLiveNavItems,
  type ChatLiveNavItem,
} from "./chat-access";
export {
  OP,
  canManagePoolHeads,
  canRemovePoolHead,
  canManageDepartmentHeads,
  canRemoveDepartmentHead,
  canDepartmentAction,
  canDesignationAction,
  canPoolAction,
  canPoolMemberAdd,
  canPoolMemberList,
  canPoolMemberMove,
  canPoolMemberRemove,
  canShiftAction,
  canOrgManageAny,
  canCompanyAction,
  hasCompaniesModulePage,
  canCompaniesModuleAction,
  canRoleAction,
  canLeaveTypeManage,
  canLeaveTypeView,
} from "./operational-keys";
